name: uni_links
description: A Flutter plugin for deep linking
version: 0.5.1
author: Rose  <roseadriennel@gmail.com>
homepage: https://github.com/avioli/uni_links

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.uni_links
        pluginClass: com.example.uni_links.UniLinksPlugin
      ios:
        pluginClass: UniLinksPlugin
